security:
    encoders:
      App\Entity\User: bcrypt

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      database_users:
        entity:
          class: App\Entity\User
          property: email

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      main:
        provider: database_users
        pattern: ^/
        anonymous: true
        switch_user: ~

        form_login:
          login_path: connection.login
          check_path: connection.login
          # Default page after success connection
          default_target_path: user.index

        logout:
          path: connection.logout
          target: homepage

    access_control:
      #Only Admin can access the pages "/admin"
      - { path: '^/admin', roles: ROLE_ADMIN }