security:
    encoders:
      App\Entity\User: bcrypt

    providers:
      database_users:
        entity: { class: App\Entity\User, property: username }

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      main:
        pattern: ^/

        anonymous: true

        form_login:
          check_path: connection.index
          login_path: connection.index
          #Form security
          csrf_token_generator: security.csrf.token_manager
          # Default page after success connection
          default_target_path: user.index

        logout:
          path: connection.logout
          target: homepage

    access_control:
      #Only Admin can access the pages "/admin"
      - { path: '^/admin', roles: ROLE_ADMIN }